apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dhondu-pvc
spec:
  storageClassName: b17g2sa
  volumeName: dhondu-pv
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    limits:
      storage: 3Gi
    requests: 
      storage: 2Gi