apiVersion: v1
kind: Secret
metadata:
  name: dhondu-secret
stringData:
  azurestorageaccountname: b17g2sa
  azurestorageaccountkey: 8jNoKVe8nZe8wiLmsRZboRwUn1I+IG3A/PnnLgAn5w/povkE8vjX9i6CErMmdCClEO5fNvIW/5v6+AStMsANkA==
type: Opaque